services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: kranthireddy152/mongodb:1.0.0
    container_name: mongodb
  catalogue:
    build:
      context: ./catalogue
    image: kranthireddy152/catalogue:1.0.0  
    container_name: catalogue
    depends_on: 
    - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kranthireddy152/frontend:1.0.0
    container_name: frontend
    ports: 
    - "80:80"
    depends_on: 
    - catalogue
    - user
    - cart
    - shipping
    - payment
  user:
    build:
      context: ./user
    image: kranthireddy152/user:1.0.0  
    container_name: user
    depends_on: 
    - redis
    - mongodb
  cart:
    build:
      context: ./cart
    image: kranthireddy152/cart:1.0.0  
    container_name: cart
    depends_on:
    - redis
    - catalogue
  redis:
    image: redis:7.0
    container_name: redis
  mysql:
    build:
      context: ./mysql
    image: kranthireddy152/mysql:1.0.0  
    container_name: mysql 
  shipping:
    build:
      context: ./shipping
    image: kranthireddy152/shipping:1.0.0  
    container_name: shipping
    depends_on: 
    - mysql   
    - cart 
  payment:
    build:
      context: ./payment
    image: kranthireddy152/payment:1.0.0  
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_PORT: "8080"
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on: 
    - rabbitmq   
    - user
    - cart 
  rabbitmq:
     image: rabbitmq:3
     environment:
        RAABIRMQ_DEFAULT_USER: roboshop
        RAABIRMQ_DEFAULT_PASS: roboshop123

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, we need to create network manually